module.exports = {
    OK: 'OK',
    INVALID_LOGIN_CREDENTIALS: 'INVALID_LOGIN_CREDENTIALS',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    USERNAME_EXISTED: 'USERNAME_EXISTED',
    PASSWORD_INCORRECT: 'PASSWORD_INCORRECT'
};