module.exports = {
    OK: 'OK',
    BAD_REQUEST: 'BAD_REQUEST',
    INVALID_LOGIN_CREDENTIALS: 'INVALID_LOGIN_CREDENTIALS',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    USERNAME_EXISTED: 'USERNAME_EXISTED',
    PASSWORD_INCORRECT: 'PASSWORD_INCORRECT',
    REGISTER_FAILED: 'REGISTER_FAILED',
    INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
    LOGOUT_FAILED : 'LOGOUT_FAILED'

};